### PR TITLE
Add configset.py to configure server.conf/sso.conf via environment variables

### PR DESCRIPTION
**Pull request by teunis90**
`configset.py` will read environment variables and path `server.conf`/`sso.conf`.

Examples:
```
sso__password__inform_if_expired=True configset.py
server__sentry__dsn=Bar configset.py

or in one go:

server__sentry__dsn=Bar sso__password__inform_if_expired=True configset.py
```

### CODE REVIEW

**Comment by teunis90** [comment]
TODO: Updating documentation.

**Comment by DimShadoWWW** [comment]
Hello @teunis90,
Thanks for the change.
We support two images with Python2.7 and Python3, you should be able to call pip from the default Python like in https://github.com/zatosource/zato/blob/main/code/_postinstall.sh#L34 .

**Comment by teunis90** [comment]
@DimShadoWWW I agree, the best thing would be to use this python Binary. I guess that will be mapped to python2.7 in the other image.
```
zato_server:/opt/zato/3.1.0/code/bin# ls -al /opt/zato/3.1.0/code/bin/python
lrwxrwxrwx 1 zato zato 7 Jun 13 13:38 /opt/zato/3.1.0/code/bin/python -> python3
```

The nice thing would be that we then also don't have to install configobj, since it's already installed. However. With that version I get this error:

```
zato_server:/usr/local/bin# configset.py
Traceback (most recent call last):
  File "/usr/local/bin/configset.py", line 10, in <module>
    server_config = configobj.ConfigObj(server_config_path)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/configobj.py", line 1236, in __init__
    self._load(infile, configspec)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/configobj.py", line 1311, in _load
    self._parse(content)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/configobj.py", line 1670, in _parse
    group = self.zato_secrets_conf.get(group_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

It looks like this version of `configobj` is patched. Maybe I should change a parameter. Does @dsuch have a good suggestion here?

**Comment by dsuch** [comment]
Hi @teunis90 - can you try with use_zato=False given to ```ConfigObj.__init__```?

**Comment by teunis90** [comment]
@DimShadoWWW @dsuch Looks like this works, waiting on automated tests.

**Comment by teunis90** [comment]
Build passed, we can merge if you ask me.

Link to test: https://travis-ci.com/Nextpertise/zato_testing/builds/138399380

**Comment by dsuch** [comment]
Hi @teunis90,

can you please also add a short docstring to configset.py with usage instructions?

Also, can you rename it to setconfig.py? I did not want to interfere with your works earlier but in Zato the convention is rather to use verb+noun.

Thanks.

**Comment by teunis90** [comment]
Processed proposed changes. Building new image and running Travis. I'll drop a message when everything is passing with the link.

**Comment by teunis90** [comment]
@dsuch I've addressed both issues. It's tested in this Travis-CI run: https://travis-ci.com/Nextpertise/zato_testing/jobs/261328837

Merge?

I've also addreessed the documentation in this PR: https://github.com/zatosource/zato-docs/pull/49

**Pull request merged**
